### ISSUE TITLE
https://wiki.hyprland.org/Nix/

### ISSUE THREAD

**Issue by bphd** [hyprwm/hyprland-wiki#381] opened 2023-11-02 15:13 UTC
`all you need in your configuration is:` `programs.hyprland.enable = true;`

Which is not true. It can't launch with that option only, complaining about a seatd issue

Workaround: launch from owner of session

**Comment by fufexan** [comment] 2023-11-02 17:01
I don't understand, what doesn't work?

**Comment by varmisa** [comment] 2023-11-20 14:05
@bphd It must work if you are not using flakes, which is not working?

**Comment by fufexan** [comment] 2024-01-31 10:42
Is this still an issue?

**Comment by bphd** [comment] 2024-03-21 07:20
> I don't understand, what doesn't work?

Well, if I read right the post, it seems not to launch as is and needs a workaround. Objective would be either to make it work as is, either to change instruction to make the workaround a real step toward making it work, idk

> @bphd It must work if you are not using flakes, which is not working? seatd issue it issue with login manager, seems like you are using something as lightdm?

Never used flakes in my Nix journey as I don't even understand them. If there is an issue with the login manager, it should be clarified in the instructions or made independent from that issue

> Is this still an issue?

Switched to another reproducible OS that needs way more steps to make HyprLand works, I'm not ready to find my env anytime soon. But the issue can't be considered solved because I don't use the program. Would be considered solved as a solution would be implemented

**Comment by fufexan** [comment] 2024-03-21 08:42
What login manager were you using? Were you launching directly from tty?

There is no problem with Hyprland itself or the Nix derivations (since it works for most Hyprland Nix users). It is most likely a problem with your system.

**Comment by bphd** [comment] 2024-03-21 09:32
> What login manager were you using? Were you launching directly from tty?
> 
> There is no problem with Hyprland itself or the Nix derivations (since it works for most Hyprland Nix users). It is most likely a problem with your system.

I talk about default configuration and explanation given in the documents, not about how my system is layed out

**Comment by fufexan** [comment] 2024-03-21 16:12
The default configuration does not imply the existence of a display manager. That's why I asked which one you were using (in case you were using one).

I do want to debug this problem, but I need all the information I can gather, since it's not a problem I can reproduce.

**Comment by bphd** [comment] 2024-03-21 16:22
> The default configuration does not imply the existence of a display manager. That's why I asked which one you were using (in case you were using one).
> 
> I do want to debug this problem, but I need all the information I can gather, since it's not a problem I can reproduce.

Well if the default configuration does not imply the existence of a display manager I shouldn't experience that problem, but like I've said

> Switched to another reproducible OS that needs way more steps to make HyprLand works, I'm not ready to find my env anytime soon. But the issue can't be considered solved because I don't use the program. Would be considered solved as a solution would be implemented

**Comment by fufexan** [comment] 2024-03-21 16:52
I take it you cannot help me debug then. I'll close the issue, and if anyone experiences it, please ping me and I'll reopen it.

**Closed by fufexan** 2024-03-21 16:52 UTC
